spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datncfs
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: congndps26169@fpt.edu.vn
    password: aegphnhmikgomzqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
